/* El Reglamento a la Ley General de Contratación Pública como dato: la
   ficha del decreto, sus ocho títulos y el índice de los 330 artículos con el
   rótulo oficial de cada uno. El texto íntegro vive en
   /datos/reglamento-contratacion.json y se descarga al abrir un artículo.
   Fuente: base de normativa de la firma, tomada del Sistema Costarricense
   de Información Jurídica. */

import type { FichaNorma } from "./normas";

export const REGLAMENTO_FICHA: FichaNorma = {
  nombre: "Reglamento a la Ley General de Contratación Pública",
  identificador: "Decreto Ejecutivo 43808-H",
  tipo: "Reglamento",
  fecha: "2022-11-22",
  version: "Texto vigente tras la reforma del Decreto 45782, publicada el 26 de mayo de 2026",
  articulos: 330,
  datos: "/datos/reglamento-contratacion.json",
  sinalevi:
    "https://sinalevi.go.cr/ResultadosNormativa/Informacion?param1=98344&param2=151216&param3=1",
  etiquetaBusqueda:
    "Escriba un número de artículo —135— o una palabra —subsanación—",
  alias: ["Reglamento de Contratación Pública", "Decreto 43808-H", "Reglamento a la Ley 9986"],
  /* La Ley 9986 cambió el nombre de casi todo. Quien busca con el
     vocabulario de la Ley 7494 encontraría un Reglamento mudo. */
  sinonimos: {
    cartel: {
      actual: "pliego de condiciones",
      nota: "Desde la Ley 9986, lo que se llamaba cartel es el pliego de condiciones.",
    },
    "cartel de licitacion": {
      actual: "pliego de condiciones",
      nota: "Desde la Ley 9986, lo que se llamaba cartel es el pliego de condiciones.",
    },
    "licitacion publica": {
      actual: "licitación mayor",
      nota: "La licitación pública se llama hoy licitación mayor.",
    },
    "licitacion abreviada": {
      actual: "licitación menor",
      nota: "La licitación abreviada se llama hoy licitación menor.",
    },
    "contratacion directa": {
      actual: "excepciones",
      nota: "La contratación directa se tramita hoy por las excepciones a los procedimientos ordinarios.",
    },
    sicop: {
      actual: "sistema digital unificado",
      nota: "El Reglamento llama al SICOP «sistema digital unificado».",
    },
    "contratacion administrativa": {
      actual: "contratación pública",
      nota: "La Ley 9986 sustituyó «contratación administrativa» por «contratación pública».",
    },
  },
};

/** Los ocho títulos del Reglamento, en su orden, y las disposiciones
 *  transitorias que lo cierran. */
export const REGLAMENTO_TITULOS: string[] = [
  "Título I · Disposiciones generales",
  "Título II · Procedimientos de contratación pública",
  "Título III · Tipos y modalidades de contrato",
  "Título IV · Régimen recursivo",
  "Título V · Ejecución contractual",
  "Título VI · Rectoría en contratación pública, juntas de adquisición y proveedurías institucionales",
  "Título VII · Disposiciones finales",
  "Disposiciones transitorias",
];

/** Los capítulos y las secciones del Reglamento. */
export const REGLAMENTO_GRUPOS: string[] = [
  "Capítulo I · Generalidades y principios",
  "Capítulo II · Actuaciones de la administración y otros sujetos",
  "Capítulo III · Contratación pública electrónica",
  "Capítulo IV · Contratación pública estratégica",
  "Capítulo I · Generalidades",
  "Capítulo II · Procedimientos ordinarios",
  "Capítulo III · Procedimientos extraordinarios",
  "Capítulo IV · Procedimientos especiales",
  "Capítulo I · Contrato de obra pública",
  "Capítulo II · Contrato de suministro",
  "Capítulo III · Contrato de donación",
  "Capítulo IV · Contrato de arrendamiento operativo y financiero",
  "Capítulo V · Contrato de servicios",
  "Capítulo VI · Contrato de fideicomiso público",
  "Capítulo VII · Concesión de instalaciones públicas",
  "Capítulo VIII · Convenio marco",
  "Capítulo IX · Tipos abiertos",
  "Capítulo II · Recurso de objeción",
  "Capítulo III · Recurso de apelación",
  "Capítulo IV · Recurso de revocatoria",
  "Capítulo II · Terminación del contrato",
  "Capítulo III · Resolución de controversias",
  "Capítulo I · Rectoría y órgano ejecutor en contratación pública",
  "Capítulo II · Proveedurías institucionales y juntas de adquisiciones",
  "Capítulo III · Profesionalización y acreditación de las unidades de compras en la contratación pública",
  "Capítulo I · Derogatoria, transitorios y vigencia",
  "Sección I · Aspectos generales",
  "Sección II · Excepciones de los procedimientos ordinarios",
  "Sección III · Aplicación de instrumentos internacionales en compras públicas",
  "Sección I · Actuaciones de la administración",
  "Sección II · Actuaciones de otros sujetos distintos a la administración",
  "Sección I · Sistema digital unificado, banco de precios, razonabilidad del precios y modelo tarifario",
  "Sección II · Compra Pública Innovadora",
  "Sección III · Participación de las Pequeñas y Medianas Empresas (Pymes) y las Cooperativas",
  "Sección II · Pliego de condiciones",
  "Sección III · Oferta",
  "Sección IV · Prácticas colusorias y anti-competitivas en los procesos de contratación.",
  "Sección V · Acto final",
  "Sección I · Licitación mayor",
  "Sección II · Licitación menor",
  "Sección III · Licitación reducida",
  "Sección I · Remate",
  "Sección II · Subasta inversa electrónica",
  "Sección I · Procedimiento de urgencia",
  "Sección II · Bienes inmuebles",
  "Sección III · Servicios en competencia",
  "Sección I · Validez, perfeccionamiento y formalización contractual",
  "Sección II · Plazo y prorrogas del contrato",
  "Sección III · Fiscalización y responsabilidades",
  "Sección IV · Recepción de bienes y servicios",
  "Sección II · Resolución del contrato",
];

/** Número de artículo, rótulo oficial, y los índices de su título, su
 *  capítulo y su sección —−1 cuando no tiene—. Va en el HTML para que el
 *  Reglamento se recorra y se rastree sin esperar a la descarga del texto. */
export const REGLAMENTO_INDICE: [string, string, number, number, number][] = [
  ["1","Ámbito de aplicación",0,0,26], ["2","Exclusiones de la aplicación de la Ley General de Contratación Pública",0,0,26], ["3","Excepciones de los procedimientos ordinarios",0,0,27],
  ["4","Requerimientos generales para el uso de las excepciones",0,0,27], ["5","Acuerdos internacionales aprobados por la Asamblea Legislativa",0,0,27], ["6","Contratación entre entes de derecho público",0,0,27],
  ["7","Proveedor único",0,0,27], ["8","Patrocinio",0,0,27], ["9","Medios de comunicación social",0,0,27],
  ["10","Servicios de capacitación abierta",0,0,27], ["11","Contratación de numerario",0,0,27], ["12","Compra con Fondos de Caja Chica",0,0,27],
  ["13","Alianzas estratégicas",0,0,27], ["14","Bienes o servicios artísticos, culturales e intelectuales",0,0,27], ["15","Reparaciones indeterminadas",0,0,27],
  ["16","Utilización de instrumentos internacionales en las Compras Públicas",0,0,28], ["17","Actuar ético y de probidad en la Contratación Pública",0,1,29], ["18","Formas de pago",0,1,29],
  ["19","Plazo para el pago y reconocimiento de intereses",0,1,29], ["20","Pago anticipado",0,1,29], ["21","Adelantos de Pagos",0,1,29],
  ["22","Bienes como parte del pago",0,1,29], ["23","Obligación de atención y cumplimiento",0,1,29], ["24","Actuar ético e íntegro de otros sujetos distintos a la Administración",0,1,30],
  ["25","Generalidades del uso del sistema digital unificado",0,2,31], ["26","Horario habilitado para el uso del sistema",0,2,31], ["27","Excepción de uso del sistema digital unificado",0,2,31],
  ["28","Expediente electrónico y conservación de la información",0,2,31], ["29","Incorporación de documentos",0,2,31], ["30","De la información confidencial en el sistema digital unificado",0,2,31],
  ["31","Información del Registro Electrónico Oficial de Proveedores y Subcontratistas",0,2,31], ["32","Requisitos para integrar el Registro Electrónico Oficial de Proveedores y Subcontratistas",0,2,31], ["33","Obligación de actualización",0,2,31],
  ["34","Causales para declarar inactivo a un proveedor o subcontratista registrado",0,2,31], ["35","Registro de poderes",0,2,31], ["36","Notificación en el sistema digital unificado",0,2,31],
  ["37","Normativa aplicable en materia de notificaciones",0,2,31], ["38","Comprobante de acuse de recibo en el sistema digital unificado",0,2,31], ["39","Registro de documentos y actos en el sistema digital unificado",0,2,31],
  ["40","Mecanismos de identificación",0,2,31], ["41","Gestión de la aplicación del modelo tarifario",0,2,31], ["42","Elementos para considerar en la definición de la tarifa para el cobro del uso del sistema digital unificado",0,2,31],
  ["43","Catálogo de Obras, Bienes y Servicios",0,2,31], ["44","Razonabilidad del Precio",0,2,31], ["45","Operatividad del uso del sistema digital unificado",0,2,31],
  ["46","Objetivos de Contratación Pública Estratégica",0,3,26], ["47","Aplicación del principio de valor por el dinero en la compra pública estratégica",0,3,26], ["48","Política pública en materia de contratación pública estratégica",0,3,26],
  ["49","Fase de prediseño de la política pública",0,3,26], ["50","Fase de diseño, implementación y gestión de la política pública",0,3,26], ["51","Fase de evaluación y monitoreo",0,3,26],
  ["52","Profesionalización para la consecución de los objetivos de compra pública estratégica",0,3,26], ["53","Convenios para la implementación de los objetivos de contratación pública estratégica",0,3,26], ["54","Mecanismos de coordinación y colaboración para la implementación de los objetivos de contratación pública estratégica",0,3,26],
  ["55","Incorporación de criterios de compra pública estratégica en los pliegos de condiciones",0,3,26], ["56","Incorporación de criterios bajo lectura de mercado",0,3,26], ["57","Criterios de vinculación al objeto contractual",0,3,26],
  ["58","Criterios objetivos y bajo normas técnicas",0,3,26], ["59","Obligación de verificación de la Administración",0,3,26], ["59bis","Criterios de innovación en Contratación Pública Estratégica",0,3,26],
  ["59ter","Utilización de mejores tecnologías",0,3,26], ["60","Compra pública innovadora",0,3,32], ["61","Parámetros de innovación",0,3,32],
  ["62","Tipos de compra pública innovadora",0,3,32], ["63","Incentivos para la innovación",0,3,32], ["64","Aspectos previos a la promoción del procedimiento",0,3,32],
  ["65","Pliego de condiciones de la compra innovadora",0,3,32], ["66","Procedimiento compra pública innovadora pre-comercial",0,3,32], ["67","Procedimiento compra pública innovadora integrada",0,3,32],
  ["68","Criterios de evaluación de la compra pública innovadora",0,3,32], ["69","Propiedad intelectual e industrial en la compra pública innovadora",0,3,32], ["70","Requisitos para el desarrollo de proyectos de investigación y/o de innovación tecnológica por esquema de asociación público privada",0,3,32],
  ["71","Presentación de propuestas novedosas por agentes económicos",0,3,32], ["72","Fomento a las PYMES",0,3,33], ["73","Estrategias para promover la participación de las PYMES",0,3,33],
  ["74","Verificación de Condición PYME",0,3,33], ["75","Compra pública consolidada para impulsar la participación de las PYMES",0,3,33], ["76","Utilización del sistema digital unificado para fomentar la contratación de las PYMES",0,3,33],
  ["77","Consorcios de PYMES",0,3,33], ["78","Grupos económicos",0,3,33], ["79","Garantías rendidas por PYMES",0,3,33],
  ["80","Programa de Adquisiciones",1,4,26], ["81","Alertas Tempranas",1,4,26], ["82","Prevalencia de la economía de escala",1,4,26],
  ["83","Prohibición de fragmentación y separación por funcionalidad",1,4,26], ["84","Promoción de la competencia",1,4,26], ["85","Sondeo, estudio de mercado y precio de referencia",1,4,26],
  ["86","Decisión inicial",1,4,26], ["87","Contenido presupuestario",1,4,26], ["88","Pliego de condiciones",1,4,34],
  ["89","Audiencias previas al pliego de condiciones",1,4,34], ["90","Contenido del pliego de condiciones",1,4,34], ["91","Condiciones invariables",1,4,34],
  ["92","Publicación y contenido de la invitación al concurso",1,4,34], ["93","Modificaciones, prórrogas y aclaraciones",1,4,34], ["94","Experiencia",1,4,34],
  ["95","Muestras",1,4,34], ["96","Sistema de evaluación",1,4,34], ["97","Desempate",1,4,34],
  ["98","Precio",1,4,34], ["99","Mejora de precios",1,4,34], ["100","Precio para efectos de comparación",1,4,34],
  ["101","Línea de crédito en caso de duda sobre la razonabilidad del precio",1,4,34], ["102","Desglose del precio",1,4,34], ["103","Sobre el presupuesto detallado",1,4,34],
  ["104","Precios unitarios y totales",1,4,34], ["105","Descuentos",1,4,34], ["106","Precio inaceptable",1,4,34],
  ["107","Derecho al mantenimiento del equilibrio económico de los costos directos e indirectos del contrato",1,4,34], ["108","Derecho al mantenimiento del equilibrio económico de los costos directos e indirectos del contrato de obra pública",1,4,34], ["109","Derecho al mantenimiento del equilibrio económico de los costos directos e indirectos en contratos de suministro de bienes y servicios",1,4,34],
  ["110","Garantía de cumplimiento",1,4,34], ["111","Forma de rendir la garantía de cumplimiento",1,4,34], ["112","Sustitución de garantía de cumplimiento y retenciones",1,4,34],
  ["113","Devolución de las garantías de cumplimiento y retenciones",1,4,34], ["114","Vigencia de la garantía de cumplimiento",1,4,34], ["115","Otras garantías y retenciones",1,4,34],
  ["116","Sanciones económicas y procedimiento de ejecución",1,4,34], ["117","Aplicación de multas y cláusulas penales",1,4,34], ["118","Generalidades de la oferta",1,4,35],
  ["119","Presentación",1,4,35], ["120","Apertura de ofertas",1,4,35], ["121","Jurisdicción",1,4,35],
  ["122","Información y documentos a aportar",1,4,35], ["123","Integridad de la oferta",1,4,35], ["124","Entrega inmediata",1,4,35],
  ["125","Tipos de ofertas",1,4,35], ["126","Participación única en cada procedimiento de contratación",1,4,35], ["127","Experiencia en consorcios",1,4,35],
  ["128","Responsabilidad en consorcios",1,4,35], ["129","Acuerdo consorcial",1,4,35], ["130","Constitución de sociedad en consorcios",1,4,35],
  ["131","Cambios de participación en el consorcio",1,4,35], ["132","Conformación de los grupos de interés económico",1,4,35], ["133","Subcontratación",1,4,35],
  ["134","Subsanación y plazo de caducidad para efectuarla",1,4,35], ["135","Aspectos subsanables",1,4,35], ["136","Estudio de admisibilidad de ofertas",1,4,35],
  ["137","Ofertas elegibles y su calificación",1,4,35], ["138","Detección de prácticas colusorias o cualquier otro tipo de práctica anti competitiva en los procedimientos de contratación",1,4,36], ["139","Acto final del procedimiento",1,4,37],
  ["140","Plazo para dictar el acto final y caducidad del procedimiento",1,4,37], ["141","Plazo para comunicar el acto final",1,4,37], ["142","Revocación del acto no firme",1,4,37],
  ["143","Definición",1,5,38], ["144","Invitación",1,5,38], ["145","Recepción de ofertas",1,5,38],
  ["146","Licitación mayor con financiamiento",1,5,38], ["147","Aspectos a considerar para la Licitación mayor con financiamiento",1,5,38], ["148","Licitación mayor con precalificación",1,5,38],
  ["149","Precalificación abierta",1,5,38], ["150","Licitación mayor por etapas",1,5,38], ["151","Supuestos de la licitación menor",1,5,39],
  ["152","Invitación",1,5,39], ["153","Recepción de ofertas",1,5,39], ["154","Definición",1,5,40],
  ["155","Invitación",1,5,40], ["156","Recepción de ofertas",1,5,40], ["157","Definición",1,6,41],
  ["158","Aspectos a considerar en el remate",1,6,41], ["159","Enajenación de bienes inmuebles",1,6,41], ["160","Subasta Inversa electrónica",1,6,42],
  ["161","Registro precalificado de la subasta inversa electrónica",1,6,42], ["162","Trámite de subasta inversa electrónica",1,6,42], ["163","Acta electrónica de la subasta",1,6,42],
  ["164","Cierre de la subasta",1,6,42], ["165","Emisión del acto final, rendición de garantía de cumplimiento y recepción de bienes y servicios",1,6,42], ["166","Contrataciones de urgencia",1,7,43],
  ["167","Compra y arrendamiento de bienes inmuebles",1,7,44], ["168","Procedimiento especial para el INS, el ICE y sus empresas en competencia, JASEC y ESPH",1,7,45], ["169","Contratación abierta de servicios para instituciones y empresas en competencia",1,7,45],
  ["170","Contratación de tecnología para instituciones y empresas en competencia",1,7,45], ["171","Generalidades",2,8,-1], ["172","Contratos de obra pública",2,8,-1],
  ["173","Calificación del personal técnico del contratista",2,8,-1], ["174","Elección de la modalidad de cotización o de pago y tipo de contrato",2,8,-1], ["175","Modalidad de cotización o de pago en el contrato de obra pública",2,8,-1],
  ["176","Tipos de contrato de obra pública",2,8,-1], ["177","Separación por unidades funcionales",2,8,-1], ["178","Ciclo de vida del proyecto. El ciclo de vida constituye el proceso de maduración y desarrollo que experimenta todo proyecto de inversión, desde la expresión de una idea hasta la operación del proyecto, en la cual se materializan los beneficios esperados. El ciclo de vida de un proyecto de inversión está conformado por tres fases las cuales son Pre-Inversión, Inversión Y Post-Inversión (operación y mantenimiento)",2,8,-1],
  ["179","Aprobación de etapas de la fase de Pre-inversión",2,8,-1], ["180","Aplicación de buenas prácticas en gestión de proyectos",2,8,-1], ["181","Expropiaciones y Unidades Funcionales de proyectos de obra pública",2,8,-1],
  ["182","Reubicación de servicios y trámites",2,8,-1], ["183","Obtención de permisos",2,8,-1], ["184","Modificación unilateral ordinaria del contrato de obra pública",2,8,-1],
  ["185","Modificación excepcional de contratos de obra pública",2,8,-1], ["186","Fiscalización y control de la obra pública",2,8,-1], ["187","Responsabilidad del contratista",2,8,-1],
  ["188","Recepción provisional de obras públicas",2,8,-1], ["189","Recepción definitiva de obras públicas",2,8,-1], ["190","Finiquito de los contratos de obra pública",2,8,-1],
  ["191","Elección de la modalidad de contrato",2,9,-1], ["192","Modalidades de contratos de suministros",2,9,-1], ["193","Contratación de suministros por cantidad definida",2,9,-1],
  ["194","Contratación de suministros por consignación",2,9,-1], ["195","Contratación de suministros, entrega según demanda",2,9,-1], ["196","Aprobación de etapas",2,9,-1],
  ["197","Periodicidad de las entregas",2,9,-1], ["198","Inspección y garantía sobre los bienes entregados",2,9,-1], ["199","Donación de bienes patrimoniales entre instituciones de la Administración Pública",2,10,-1],
  ["200","Donación de bienes muebles patrimoniales entre instituciones de la Administración Pública",2,10,-1], ["201","Donación de bienes inmuebles patrimoniales entre instituciones de la Administración Pública",2,10,-1], ["202","Donación de bienes muebles e inmuebles patrimoniales en desuso o mal estado entre instituciones de la Administración Pública o a entidades privadas",2,10,-1],
  ["203","Contrato de arrendamiento operativo",2,11,-1], ["204","Contrato de arrendamiento financiero",2,11,-1], ["205","Objeto del contrato de arrendamiento financiero",2,11,-1],
  ["206","Requerimientos mínimos del contrato de arrendamiento financiero",2,11,-1], ["207","Aplicación de la normativa contable en que se basa el tratamiento contable de los arrendamientos financieros en instituciones del sector no financiero",2,11,-1], ["208","Aprobaciones",2,11,-1],
  ["209","Estructuración del arrendamiento",2,11,-1], ["210","Criterio de escogencia del arrendador",2,11,-1], ["211","Plazo",2,11,-1],
  ["212","Objeto de la contratación de servicios",2,12,-1], ["213","Selección del contratista",2,12,-1], ["214","Pago en contrato de servicios",2,12,-1],
  ["215","Información necesaria para la ejecución del objeto contractual",2,12,-1], ["216","Fideicomisos públicos",2,13,-1], ["217","Partes del contrato de fideicomiso público",2,13,-1],
  ["218","Relación entre el fideicomitente y el fiduciario",2,13,-1], ["219","Selección de fiduciario",2,13,-1], ["220","Comisión de la fiducia",2,13,-1],
  ["221","Administración de conflictos de interés",2,13,-1], ["222","Constitución de fideicomisos que requieran financiamiento",2,13,-1], ["223","Constitución de fideicomisos de obra pública",2,13,-1],
  ["224","Bancabilidad de los fideicomisos de obra pública",2,13,-1], ["225","Políticas de administración de fideicomisos de obra pública",2,13,-1], ["226","Unidades de Administración",2,13,-1],
  ["227","Concesión de instalaciones públicas",2,14,-1], ["228","Convenio Marco",2,15,-1], ["229","Plazo contractual del convenio marco",2,15,-1],
  ["230","Etapas",2,15,-1], ["231","Modelos de Convenio Marco",2,15,-1], ["232","Uso de criterios de compra pública estratégica en los convenios marco",2,15,-1],
  ["233","Ofertas",2,15,-1], ["234","Inclusiones de nuevas opciones de negocio",2,15,-1], ["235","Mejoras de precios en las opciones de negocio",2,15,-1],
  ["236","Sistemas de Convenio Marco",2,15,-1], ["237","Obligaciones de las Instituciones Usuarias",2,15,-1], ["238","Obligaciones de los Contratistas",2,15,-1],
  ["239","Generalidades",2,16,-1], ["240","Registro de reglamento de tipo abierto",2,16,-1], ["241","Taxatividad de los recursos",3,4,26],
  ["242","Cómputo del plazo",3,4,26], ["243","Presentación",3,4,26], ["244","Rechazo de plano por inadmisibilidad",3,4,26],
  ["245","Rechazo de plano por improcedencia manifiesta",3,4,26], ["246","Deber de fundamentación",3,4,26], ["247","Vicios de nulidad absoluta, evidente y manifiesta",3,4,26],
  ["248","Nulidades alegadas en el recurso en caso de rechazo por inadmisibilidad o improcedencia",3,4,26], ["249","Allanamiento y desistimiento del recurso",3,4,26], ["250","Preclusión",3,4,26],
  ["251","Diligencias de adición y aclaración",3,4,26], ["252","Régimen recursivo en contrataciones efectuadas con normativa de sujetos de derecho público internacional",3,4,26], ["253","Presentación y legitimación en el recurso de objeción en general",3,17,-1],
  ["254","Recurso de objeción tramitado ante la Contraloría General de la República",3,17,-1], ["255","Recurso de objeción de la licitación menor y licitación reducida tramitados ante la Administración",3,17,-1], ["256","Recurso de objeción a modificaciones al pliego de condiciones",3,17,-1],
  ["257","Efectos de la interposición y de la resolución del recurso de objeción presentado ante la Contraloría General de la República",3,17,-1], ["258","Efectos de la interposición y de la resolución del recurso de objeción presentado ante la propia Administración",3,17,-1], ["259","Supuestos",3,18,-1],
  ["260","Procedencia",3,18,-1], ["261","Legitimación",3,18,-1], ["262","Fundamentación",3,18,-1],
  ["263","Admisibilidad del recurso",3,18,-1], ["264","Trámite de procedencia del recurso",3,18,-1], ["265","Supuestos de inadmisibilidad",3,18,-1],
  ["266","Supuestos de improcedencia manifiesta",3,18,-1], ["267","Efectos de la interposición y de la resolución que resuelve el recurso de apelación",3,18,-1], ["268","Prórroga para resolver",3,18,-1],
  ["269","Acumulación de recursos",3,18,-1], ["270","Procedencia del recurso de revocatoria",3,19,-1], ["271","Trámite de procedencia del recurso",3,19,-1],
  ["272","Elementos del contrato",4,4,46], ["273","Validez",4,4,46], ["274","Perfeccionamiento y formalización contractual",4,4,46],
  ["275","Procedimiento de Formalización Contractual",4,4,46], ["276","Modificación unilateral del contrato de bienes y servicios",4,4,46], ["277","Cesión",4,4,46],
  ["278","Cesión de los derechos de pago",4,4,46], ["279","Contratación Irregular",4,4,46], ["280","Plazo del contrato y prórrogas",4,4,47],
  ["281","Prórrogas al plazo de ejecución del contrato",4,4,47], ["282","Suspensión del plazo y de la ejecución del contrato",4,4,47], ["283","Fiscalización y control",4,4,48],
  ["284","Recepción provisional de bienes y servicios",4,4,49], ["285","Recepción definitiva de bienes y servicios",4,4,49], ["286","Rechazo del objeto",4,4,49],
  ["287","Recibo de bienes actualizados",4,4,49], ["288","Terminación del contrato",4,20,26], ["289","Rescate del servicio para ser explotado directamente por la Administración",4,20,26],
  ["290","Supresión del servicio por razones de interés público",4,20,26], ["291","Finiquito de los contratos de servicios y suministro de bienes",4,20,26], ["292","Caducidad",4,20,26],
  ["293","Resolución del contrato",4,20,50], ["294","Resolución controversias",4,21,-1], ["295","Centro de Resolución de Controversias",4,21,-1],
  ["296","Comité de expertos",4,21,-1], ["297","Comité de expertos en las licitaciones mayores de obra pública",4,21,-1], ["298","Comité ad hoc de expertos",4,21,-1],
  ["299","Nombramiento del Comité de Expertos",4,21,-1], ["300","De los requisitos para ser miembros de los comités de expertos",4,21,-1], ["301","Independencia e imparcialidad de los expertos",4,21,-1],
  ["302","Deber de información",4,21,-1], ["303","Plazo para emitir criterio",4,21,-1], ["304","Vinculancia de la decisión del comité de expertos",4,21,-1],
  ["305","Honorarios y gastos",4,21,-1], ["306","Nombramiento del director y subdirector de la Dirección de Contratación Pública",5,22,-1], ["307","Impedimentos",5,22,-1],
  ["308","Funciones de la Dirección de Contratación Pública",5,22,-1], ["309","Materia consultiva en Contratación Pública",5,22,-1], ["310","Elaboración del Plan Nacional de Compra Pública y emisión de directrices",5,22,-1],
  ["311","Administración de los riesgos en materia de contratación pública",5,22,-1], ["312","Requerimiento de información a las instituciones del sector público",5,22,-1], ["313","Conformación de registro único de sanciones a particulares",5,22,-1],
  ["314","Definición funcional de Proveedurías Institucionales y Juntas de adquisiciones",5,23,-1], ["315","Personal de la Proveeduría institucional",5,23,-1], ["316","De la tramitación por medio del sistema digital unificado",5,23,-1],
  ["317","De la posibilidad de delegación",5,23,-1], ["318","De las Juntas de Adquisiciones y Comisión de Recomendación de Adjudicaciones",5,23,-1], ["319","Obligada colaboración",5,23,-1],
  ["320","Estrategia de profesionalización en contratación pública",5,24,-1], ["321","Formación",5,24,-1], ["322","Proceso de profesionalización",5,24,-1],
  ["323","Vigencia de la certificación de idoneidad en compras públicas",5,24,-1], ["324","Estrategia para la acreditación de las unidades de compra",5,24,-1], ["325","Requisitos para la acreditación de Unidades de Compras Institucionales",5,24,-1],
  ["326","Acreditación de Unidades de Compras Públicas",5,24,-1], ["327","Derogatoria",6,25,-1], ["TI","Transitorio I",7,-1,-1],
  ["TII","Transitorio II",7,-1,-1], ["TIII","Transitorio III",7,-1,-1], ["TIV","Transitorio IV",7,-1,-1],
  ["TV","Transitorio V",7,-1,-1], ["TVI","Transitorio VI",7,-1,-1], ["TVII","Transitorio VII",7,-1,-1],
  ["TVIII","Transitorio VIII",7,-1,-1], ["TIX","Transitorio IX",7,-1,-1], ["328","Rige",6,25,-1],
];

/** Artículos que el Reglamento ya derogó: se marcan en la lista para que
 *  nadie los cite creyéndolos vigentes. */
export const REGLAMENTO_DEROGADOS: string[] = ["61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71"];

/** Guías de la casa que explican lo que un artículo regula. */
export const REGLAMENTO_GUIAS: Record<string, { href: string; texto: string }> = {
  "107": { href: "/articulos/reajuste-precios-obra-publica-costa-rica", texto: "Cómo se pide el reajuste de precios" },
  "108": { href: "/articulos/reajuste-precios-obra-publica-costa-rica", texto: "Cómo se pide el reajuste de precios" },
  "109": { href: "/articulos/reajuste-precios-obra-publica-costa-rica", texto: "Cómo se pide el reajuste de precios" },
  "116": { href: "/articulos/sanciones-a-proveedores-contratacion-publica-ley-9986", texto: "Las sanciones al proveedor del Estado" },
  "241": { href: "/articulos/recursos-contratacion-publica-objecion-apelacion-revocatoria", texto: "Qué recurso cabe en cada caso" },
  "253": { href: "/articulos/recurso-objecion-cartel-costa-rica", texto: "Cómo objetar el cartel" },
  "254": { href: "/articulos/recurso-objecion-cartel-costa-rica", texto: "Cómo objetar el cartel" },
  "255": { href: "/articulos/recurso-objecion-cartel-costa-rica", texto: "Cómo objetar el cartel" },
  "256": { href: "/articulos/recurso-objecion-cartel-costa-rica", texto: "Cómo objetar el cartel" },
  "263": { href: "/articulos/recurso-apelacion-adjudicacion-cgr-costa-rica", texto: "Cómo apelar una adjudicación ante la Contraloría" },
  "264": { href: "/articulos/recurso-apelacion-adjudicacion-cgr-costa-rica", texto: "Cómo apelar una adjudicación ante la Contraloría" },
  "267": { href: "/articulos/anular-adjudicacion-tribunal-contencioso-administrativo", texto: "Cuando la adjudicación se discute en el Tribunal" },
  "270": { href: "/articulos/recursos-contratacion-publica-objecion-apelacion-revocatoria", texto: "La revocatoria ante la propia Administración" },
  "271": { href: "/articulos/recursos-contratacion-publica-objecion-apelacion-revocatoria", texto: "La revocatoria ante la propia Administración" },
  "313": { href: "/articulos/defensa-inhabilitacion-proveedor-estado-costa-rica", texto: "Defensa frente a una inhabilitación" },
};
